osx_image: xcode8.2
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script: 
  - echo "https://api.sightr.io/uploadscript?branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&repoKey=594aca5834287328edb4f1be&directory=screenshots&commit=$TRAVIS_COMMIT"
  - curl "https://api.sightr.io/uploadscript?branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&repoKey=594aca5834287328edb4f1be&directory=screenshots&commit=$TRAVIS_COMMIT" | bash
