osx_image: xcode8.2
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script: curl "https://api.sightr.io/uploadscript?branch=$TRAVIS_BRANCH&ci=travis&build=$TRAVIS_BUILD_NUMBER&repoKey=5952bdaeb0bb6e04a875614e&directory=screenshots&commit=$TRAVIS_COMMIT" | bash
